name: YAPF Code Formatter

on: [push]

jobs:
  Formatter:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: yapf formatter action
    - uses: diegovalenzuelaiturra/yapf-action@master
